url: "http://xpcassio.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
baseavatar: "/assets/images/xpcassio_alt.jpg" # /assets/images/xpcassio.png

collections:
  projetos:
    output: true

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 1
  permalink: '/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'posts'